### ISSUE TITLE
Datatypes with duplicate names

### ISSUE THREAD

**Issue by fmagin** [Katharsas/ghidra-struct-importer#1]
Your README says:
> Dot not parse datatypes with names that already exist anywhere, regardless of in which category, otherwise type might end up with wrong name

I think the solution for this is to use an appropriate [`DataTypeConflictHandler`](https://ghidra.re/ghidra_docs/api/ghidra/program/model/data/DataTypeConflictHandler.html) in this line instead of `null`
https://github.com/Katharsas/ghidra-struct-importer/blob/1ae2ec69d723d25ec22da390c32920bcb2d08f02/ImportCStruct.java#L241

The default one implicitly used does a "rename and add" and probably leads to the issue described in the README.

**Comment by Katharsas** [comment]
Cool thanks, ill try that!

**Comment by Katharsas** [comment]
Hey @fmagin 

The big problem im seeing here is that the "Parse" Button is already seemingly modifying the state of the global DataTypeManager. Simply executing the line `type = parser.parse(text);` can already override existing types, if a struct with existing name was parsed. The `apply` button does not need to be pressed at all.

The reason seems to be that the parser actually adds/overwrites datatypes on parsing. The line `type = parser.parse(text);` will call `dtMgr.startTransaction("Parsing");` by itself, the apply button is not needed. This happens because the parser is instantiated with our global DataTypeManager (`var parser = new CParser(dtm);`).

I think to make this work as expected (only modify program state when apply button is actually pressed) i have to pass a temporary DTM that acts as dataType buffer, but can still resolve referenced types from the global DTM. I will look into that.

**Comment by Katharsas** [comment]
Ok i implemented [BufferedDataTypeManager ](https://github.com/Katharsas/ghidra-struct-importer/blob/e6f3b84026d2b1650addb0551a99174552467e33/structimporter/BufferedDataTypeManager.java) in the latest commit, and it fixes the the main issue (datatypes do no longer get added on parse, only on save). I tried to basically implement a combined view onto two underlying DataTypeManagers:  
- a standalone in-memory DTM as buffer
- the global program DTM

It does resolve DataTypes from the global program DTM during parsing without changing that DTM, so that is great.

**However**, i have a problem with the current implementation:

The successfully parsed datatypes do not actually get saved inside the buffer, they simply disappear. The only reason why i do no loose them entirely is that i get the last parsed DataType from the parser directly, just as in the original implementation.

So now, we cannot:  
- parse multiple structs at once because all except the last one disappear
- have multiple parsed structs depend on each other because that would require `BufferedDataTypeManager` to resolve them to each other which it does not do because it is always empty

I guess the way in which i implemented `BufferedDataTypeManager` breaks the parent class `StandAloneDataTypeManager` somewhat, but im not sure why.

**Comment by Katharsas** [comment]
Actually what i said [earlier](https://github.com/Katharsas/ghidra-struct-importer/issues/1#issuecomment-1317934651) about the parser adding/overwriting datatypes on parsing is probably not true. I tried it again and i can no longer reproduce that behaviour unless is explicitely set `storeDataType = true`;

**Comment by Katharsas** [comment]
Ok i was just being stupid. CParser literally has methods that allow getting all parsed DataTypes without having to use the `storeDataType` flag at all, which means that dependency resolution also works. Should now be properly implemented in https://github.com/Katharsas/ghidra-struct-importer/commit/a1b47aa4ae742e200abcf71b54c39f49b6d9cbce.
